### ISSUE TITLE
enable yml for different environments

### ISSUE THREAD

**Issue by Fuin** [jacekk/codeception-dataprovider-module#1]
Hey, 
I am using your dataprovider for my codeception tests and its helping me a lot. 
I just ran into a problem when I tried to enable different ymls for different environments. 
So far I have three different yml files, one common which I enabled in the config and two other which I enabled just for different environments
My yml looks like this

```yml
class_name: AcceptanceTester
modules:
    enabled:
        - WebDriver
        - Helper\Acceptance
        - DataProvider
        - Asserts

    config:
        WebDriver:
            url: 'https://'
            browser: 'chrome'
        DataProvider:
            dataPathTpl: '{root}/tests/_data/{file}'
            files:
                - common-provider.yml
env:
    dev:
        modules:
            config:
                WebDriver:
                    url: 'http://'
                    browser: 'chrome'
                DataProvider:
                    files:
                        - env-provider.dev.yml

    stage:
        modules:
            config:
                WebDriver:
                    url: 'https://'
                    browser: 'chrome'
                DataProvider:
                    files:
                        - env-provider.stage.yml

    desktop:
        modules:
            config:
                WebDriver:
                    window_size: 1600x768

    grid:
        modules:
            config:
                WebDriver:
                    host: '10.0.5.80'
                    port: 4444
```

its working fine as long as I only run one environment at a time, but the things inside the common-provider are inserted twice when I run for example --env desktop,dev
its really unfortunate because for my tests I need to run different environments with different window sizes together
